# 开发环境配置文件
# 此文件包含开发环境的默认配置
# 不包含敏感信息，可以安全地提交到版本控制

server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: postgres
    # 开发环境数据库连接
    source: postgresql://postgres:postgres@localhost:5432/test_dev?sslmode=disable
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s

auth:
  # 开发环境JWT密钥 - 仅用于开发环境，生产环境必须使用强随机密钥
  jwt_secret_key: "dev-jwt-secret-key-change-in-production"
  access_token_expiration: "24h"
  refresh_token_expiration: "7d"
  captcha_enabled: true
  captcha_expiration: "5m"
  max_login_attempts: 5
  lock_duration: "30m"
  totp_enabled: false

plugins:
  enabled: true
  directory: "./plugins"
  config_directory: "./configs/plugins"
  auto_load: true
  security:
    sandbox_enabled: true
    max_memory: "100MB"
    max_cpu_percent: 10

# Monitoring configuration
monitoring:
  metrics:
    enabled: true
    path: "/metrics"
  health:
    enabled: true
    path: "/health"
