features:
  # 禁用高级报表功能
  report.advanced:
    enabled: false

  # 限制系统配置功能
  system.config:
    enabled: true
    apis:
      - "GET /api/v1/system/config" # 只保留查看，移除编辑
    routes:
      - "/admin/system/config"

  # 限制用户安全功能
  user.security:
    enabled: true
    apis:
      - "POST /api/v1/auth/password" # 只保留密码修改，移除TOTP
    routes:
      - "/security/password"
    configs:
      - "security.password_policy"
