# 生产环境功能开关配置
# 继承基础配置，覆盖特定功能

# 生产环境中禁用调试功能
swagger_ui:
  enabled: false
  strategy: simple
  rules: {}
  description: "生产环境中禁用Swagger UI"
  tags: ["api", "documentation", "prod"]

debug_mode:
  enabled: false
  strategy: simple
  rules: {}
  description: "生产环境中禁用调试模式"
  tags: ["prod", "debug"]

# 生产环境中启用所有安全功能
rate_limit:
  enabled: true
  strategy: simple
  rules: {}
  description: "生产环境中启用API限流"
  tags: ["api", "performance", "prod"]

account_lockout:
  enabled: true
  strategy: simple
  rules: {}
  description: "生产环境中启用账户锁定"
  tags: ["auth", "security", "prod"]

data_encryption:
  enabled: true
  strategy: simple
  rules: {}
  description: "生产环境中启用数据加密"
  tags: ["data", "security", "prod"]

# 生产环境中谨慎使用Beta功能
beta_features:
  enabled: true
  strategy: user
  rules:
    user_types: ["internal", "beta_tester"]
    whitelist: ["admin@company.com", "test@company.com"]
  description: "生产环境中限制Beta功能访问"
  tags: ["experimental", "beta", "prod"]

# 新功能渐进式发布
new_user_dashboard:
  enabled: true
  strategy: percentage
  rules:
    percentage: 5.0 # 生产环境中只对5%的用户启用
  description: "新版用户仪表盘渐进式发布"
  tags: ["ui", "rollout", "prod"]

# 监控功能在生产环境中全部启用
metrics:
  enabled: true
  strategy: simple
  rules: {}
  description: "生产环境指标收集"
  tags: ["monitoring", "observability", "prod"]

tracing:
  enabled: true
  strategy: simple
  rules: {}
  description: "生产环境链路追踪"
  tags: ["monitoring", "observability", "prod"]

health_check:
  enabled: true
  strategy: simple
  rules: {}
  description: "生产环境健康检查"
  tags: ["monitoring", "health", "prod"]
