# 功能开关配置文件

# 分层功能集合
# 用户功能域
user.management:
  enabled: true
  strategy: simple
  permissions:
    - "user.create"
    - "user.update"
    - "user.delete"
    - "user.list"
  audit_logs:
    - "user_created"
    - "user_updated"
    - "user_deleted"
  apis:
    - "POST /api/v1/users"
    - "PUT /api/v1/users/{id}"
    - "DELETE /api/v1/users/{id}"
    - "GET /api/v1/users"
  routes:
    - "/admin/users"
    - "/admin/users/create"
  configs:
    - "user.max_count"
    - "user.password_policy"
  description: "用户管理功能集合"
  tags: ["user", "admin"]
  created_at: "2025-01-10T10:00:00Z"
  updated_at: "2025-01-10T10:00:00Z"

user.profile:
  enabled: true
  strategy: simple
  permissions:
    - "profile.view"
    - "profile.edit"
  audit_logs:
    - "profile_updated"
  apis:
    - "GET /api/v1/profile"
    - "PUT /api/v1/profile"
  routes:
    - "/profile"
    - "/profile/edit"
  configs:
    - "profile.avatar_size"
  description: "用户资料功能集合"
  tags: ["user", "profile"]
  created_at: "2025-01-10T10:00:00Z"
  updated_at: "2025-01-10T10:00:00Z"

user.security:
  enabled: true
  strategy: simple
  permissions:
    - "security.password_change"
    - "security.totp_manage"
  audit_logs:
    - "password_changed"
    - "totp_enabled"
  apis:
    - "POST /api/v1/auth/password"
    - "POST /api/v1/auth/totp"
  routes:
    - "/security/password"
    - "/security/totp"
  configs:
    - "security.password_policy"
    - "security.totp_required"
  description: "用户安全功能集合"
  tags: ["user", "security"]
  created_at: "2025-01-10T10:00:00Z"
  updated_at: "2025-01-10T10:00:00Z"

# 系统功能域
system.config:
  enabled: true
  strategy: environment
  rules:
    environments: ["development", "staging", "production"]
  permissions:
    - "system.config.view"
    - "system.config.edit"
  audit_logs:
    - "system_config_changed"
  apis:
    - "GET /api/v1/system/config"
    - "PUT /api/v1/system/config"
  routes:
    - "/admin/system/config"
  configs:
    - "system.debug_mode"
    - "system.log_level"
  description: "系统配置功能集合"
  tags: ["system", "admin"]
  created_at: "2025-01-10T10:00:00Z"
  updated_at: "2025-01-10T10:00:00Z"

system.monitoring:
  enabled: true
  strategy: simple
  permissions:
    - "monitoring.view"
    - "monitoring.alerts"
  audit_logs:
    - "alert_configured"
  apis:
    - "GET /api/v1/monitoring/metrics"
    - "GET /api/v1/monitoring/alerts"
  routes:
    - "/admin/monitoring"
  configs:
    - "monitoring.retention_days"
  description: "系统监控功能集合"
  tags: ["system", "monitoring"]
  created_at: "2025-01-10T10:00:00Z"
  updated_at: "2025-01-10T10:00:00Z"

# 报表功能域
report.basic:
  enabled: true
  strategy: simple
  permissions:
    - "report.basic.view"
  audit_logs:
    - "basic_report_generated"
  apis:
    - "GET /api/v1/reports/basic"
  routes:
    - "/reports/basic"
  configs:
    - "report.max_records"
  description: "基础报表功能集合"
  tags: ["report", "basic"]
  created_at: "2025-01-10T10:00:00Z"
  updated_at: "2025-01-10T10:00:00Z"

report.advanced:
  enabled: true
  strategy: user
  rules:
    user_types: ["admin", "premium"]
  permissions:
    - "report.advanced.view"
    - "report.advanced.export"
  audit_logs:
    - "advanced_report_generated"
    - "report_exported"
  apis:
    - "GET /api/v1/reports/advanced"
    - "POST /api/v1/reports/export"
  routes:
    - "/reports/advanced"
  configs:
    - "report.export_formats"
  description: "高级报表功能集合"
  tags: ["report", "premium"]
  created_at: "2025-01-10T10:00:00Z"
  updated_at: "2025-01-10T10:00:00Z"

# 向后兼容 - 原有功能开关
captcha:
  enabled: true
  strategy: simple
  rules: {}
  description: "验证码功能开关"
  tags: ["auth", "security"]
  created_at: "2025-01-10T10:00:00Z"
  updated_at: "2025-01-10T10:00:00Z"

totp:
  enabled: false
  strategy: user
  rules:
    user_types: ["admin", "premium"]
  description: "TOTP双因子认证开关"
  tags: ["auth", "security", "2fa"]
  created_at: "2025-01-10T10:00:00Z"
  updated_at: "2025-01-10T10:00:00Z"

password_policy:
  enabled: true
  strategy: simple
  rules: {}
  description: "密码策略检查开关"
  tags: ["auth", "security"]
  created_at: "2025-01-10T10:00:00Z"
  updated_at: "2025-01-10T10:00:00Z"

account_lockout:
  enabled: true
  strategy: simple
  rules: {}
  description: "账户锁定功能开关"
  tags: ["auth", "security"]
  created_at: "2025-01-10T10:00:00Z"
  updated_at: "2025-01-10T10:00:00Z"

# API相关功能
rate_limit:
  enabled: true
  strategy: environment
  rules:
    environments: ["production", "staging"]
  description: "API限流功能开关"
  tags: ["api", "performance"]
  created_at: "2025-01-10T10:00:00Z"
  updated_at: "2025-01-10T10:00:00Z"

api_versioning:
  enabled: true
  strategy: simple
  rules: {}
  description: "API版本控制开关"
  tags: ["api", "compatibility"]
  created_at: "2025-01-10T10:00:00Z"
  updated_at: "2025-01-10T10:00:00Z"

swagger_ui:
  enabled: true
  strategy: environment
  rules:
    environments: ["development", "staging"]
  description: "Swagger UI开关"
  tags: ["api", "documentation"]
  created_at: "2025-01-10T10:00:00Z"
  updated_at: "2025-01-10T10:00:00Z"

# 数据相关功能
data_encryption:
  enabled: true
  strategy: simple
  rules: {}
  description: "数据加密功能开关"
  tags: ["data", "security"]
  created_at: "2025-01-10T10:00:00Z"
  updated_at: "2025-01-10T10:00:00Z"

audit_log:
  enabled: true
  strategy: simple
  rules: {}
  description: "审计日志功能开关"
  tags: ["data", "audit", "compliance"]
  created_at: "2025-01-10T10:00:00Z"
  updated_at: "2025-01-10T10:00:00Z"

sensitive_data:
  enabled: true
  strategy: simple
  rules: {}
  description: "敏感数据处理开关"
  tags: ["data", "security", "privacy"]
  created_at: "2025-01-10T10:00:00Z"
  updated_at: "2025-01-10T10:00:00Z"

# 插件相关功能
plugin_system:
  enabled: true
  strategy: simple
  rules: {}
  description: "插件系统开关"
  tags: ["plugin", "extensibility"]
  created_at: "2025-01-10T10:00:00Z"
  updated_at: "2025-01-10T10:00:00Z"

plugin_sandbox:
  enabled: true
  strategy: simple
  rules: {}
  description: "插件沙盒功能开关"
  tags: ["plugin", "security"]
  created_at: "2025-01-10T10:00:00Z"
  updated_at: "2025-01-10T10:00:00Z"

# 运维相关功能
metrics:
  enabled: true
  strategy: simple
  rules: {}
  description: "指标收集功能开关"
  tags: ["monitoring", "observability"]
  created_at: "2025-01-10T10:00:00Z"
  updated_at: "2025-01-10T10:00:00Z"

tracing:
  enabled: true
  strategy: simple
  rules: {}
  description: "链路追踪功能开关"
  tags: ["monitoring", "observability"]
  created_at: "2025-01-10T10:00:00Z"
  updated_at: "2025-01-10T10:00:00Z"

health_check:
  enabled: true
  strategy: simple
  rules: {}
  description: "健康检查功能开关"
  tags: ["monitoring", "health"]
  created_at: "2025-01-10T10:00:00Z"
  updated_at: "2025-01-10T10:00:00Z"

# 示例：渐进式发布配置
new_user_dashboard:
  enabled: true
  strategy: percentage
  rules:
    percentage: 10.0 # 10%的用户启用新版仪表盘
  description: "新版用户仪表盘渐进式发布"
  tags: ["ui", "rollout"]
  created_at: "2025-01-10T10:00:00Z"
  updated_at: "2025-01-10T10:00:00Z"

# 示例：基于时间的功能开关
holiday_theme:
  enabled: false
  strategy: time
  rules:
    start_time: "2025-12-20T00:00:00Z"
    end_time: "2026-01-05T23:59:59Z"
  description: "节日主题开关"
  tags: ["ui", "seasonal"]
  created_at: "2025-01-10T10:00:00Z"
  updated_at: "2025-01-10T10:00:00Z"

# 示例：基于用户属性的功能开关
beta_features:
  enabled: true
  strategy: user
  rules:
    user_types: ["beta_tester", "internal"]
    attributes:
      role: "admin"
  description: "Beta功能开关"
  tags: ["experimental", "beta"]
  created_at: "2025-01-10T10:00:00Z"
  updated_at: "2025-01-10T10:00:00Z"
