features:
  # 用户功能域
  user.management:
    enabled: true
    strategy: simple
    permissions:
      - "user.create"
      - "user.update"
      - "user.delete"
      - "user.list"
    audit_logs:
      - "user_created"
      - "user_updated"
      - "user_deleted"
    apis:
      - "POST /api/v1/users"
      - "PUT /api/v1/users/{id}"
      - "DELETE /api/v1/users/{id}"
      - "GET /api/v1/users"
    routes:
      - "/admin/users"
      - "/admin/users/create"
    configs:
      - "user.max_count"
      - "user.password_policy"
    description: "用户管理功能集合"
    tags: ["user", "admin"]

  user.profile:
    enabled: true
    strategy: simple
    permissions:
      - "profile.view"
      - "profile.edit"
    audit_logs:
      - "profile_updated"
    apis:
      - "GET /api/v1/profile"
      - "PUT /api/v1/profile"
    routes:
      - "/profile"
      - "/profile/edit"
    configs:
      - "profile.avatar_size"
    description: "用户资料功能集合"
    tags: ["user", "profile"]

  user.security:
    enabled: true
    strategy: simple
    permissions:
      - "security.password_change"
      - "security.totp_manage"
    audit_logs:
      - "password_changed"
      - "totp_enabled"
    apis:
      - "POST /api/v1/auth/password"
      - "POST /api/v1/auth/totp"
    routes:
      - "/security/password"
      - "/security/totp"
    configs:
      - "security.password_policy"
      - "security.totp_required"
    description: "用户安全功能集合"
    tags: ["user", "security"]

  # 系统功能域
  system.config:
    enabled: true
    strategy: environment
    rules:
      environments: ["development", "staging", "production"]
    permissions:
      - "system.config.view"
      - "system.config.edit"
    audit_logs:
      - "system_config_changed"
    apis:
      - "GET /api/v1/system/config"
      - "PUT /api/v1/system/config"
    routes:
      - "/admin/system/config"
    configs:
      - "system.debug_mode"
      - "system.log_level"
    description: "系统配置功能集合"
    tags: ["system", "admin"]

  system.monitoring:
    enabled: true
    strategy: simple
    permissions:
      - "monitoring.view"
      - "monitoring.alerts"
    audit_logs:
      - "alert_configured"
    apis:
      - "GET /api/v1/monitoring/metrics"
      - "GET /api/v1/monitoring/alerts"
    routes:
      - "/admin/monitoring"
    configs:
      - "monitoring.retention_days"
    description: "系统监控功能集合"
    tags: ["system", "monitoring"]

  # 报表功能域
  report.basic:
    enabled: true
    strategy: simple
    permissions:
      - "report.basic.view"
    audit_logs:
      - "basic_report_generated"
    apis:
      - "GET /api/v1/reports/basic"
    routes:
      - "/reports/basic"
    configs:
      - "report.max_records"
    description: "基础报表功能集合"
    tags: ["report", "basic"]

  report.advanced:
    enabled: true
    strategy: user
    rules:
      user_types: ["admin", "premium"]
    permissions:
      - "report.advanced.view"
      - "report.advanced.export"
    audit_logs:
      - "advanced_report_generated"
      - "report_exported"
    apis:
      - "GET /api/v1/reports/advanced"
      - "POST /api/v1/reports/export"
    routes:
      - "/reports/advanced"
    configs:
      - "report.export_formats"
    description: "高级报表功能集合"
    tags: ["report", "premium"]
