# 开发环境功能开关配置
# 继承基础配置，覆盖特定功能

# 开发环境中启用调试功能
swagger_ui:
  enabled: true
  strategy: simple
  rules: {}
  description: "开发环境中启用Swagger UI"
  tags: ["api", "documentation", "dev"]

# 开发环境中禁用某些安全检查以便于测试
rate_limit:
  enabled: false
  strategy: simple
  rules: {}
  description: "开发环境中禁用限流以便于测试"
  tags: ["api", "performance", "dev"]

# 开发环境中启用所有Beta功能
beta_features:
  enabled: true
  strategy: simple
  rules: {}
  description: "开发环境中启用所有Beta功能"
  tags: ["experimental", "beta", "dev"]

# 开发环境中启用详细日志
audit_log:
  enabled: true
  strategy: simple
  rules: {}
  description: "开发环境中启用详细审计日志"
  tags: ["data", "audit", "dev"]

# 测试专用功能
mock_external_services:
  enabled: true
  strategy: simple
  rules: {}
  description: "开发环境中使用Mock外部服务"
  tags: ["dev", "testing", "mock"]

debug_mode:
  enabled: true
  strategy: simple
  rules: {}
  description: "开发环境调试模式"
  tags: ["dev", "debug"]
